---
- hosts: mywebservers
  become: yes
  tasks:
  - name: install java ubuntu
    apt:
      name: "{{javapackonubuntu}}"
      state: present
    when: ansible_os_family =="Debian"

  - name: install java on Redhat
    ansible.builtin.dnf:
      name: "{{javapackonredhat}}"
      state: present
  when: ansible_os_family =="RedHat"
 
