---
- hosts: mywebservers
  become: yes
  tasks:
- name: install java on ubuntu
  apt:
    name: "{{installjavaonubuntu}}"
    state: present
  when: ansible_os_family== "Debian"
- name: install java on Redhat
  ansible.builtin.dnf:
     name: "{{installjavaonredhat}}"
     state: present
  when: ansible_os_family=="RedHat"
 
